//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;

public class ZigShip : Entity{

	protected float lowerBound;
	protected int dir = 1;
	protected float upperBound;

	protected void Start(){
		this.speed = 4;
		upperBound = transform.position.y + 4;
		lowerBound = transform.position.y - 4;
		base.Start();
	}

	void Update () {
		if (transform.position.x > endPoint) {
			move (new Vector2(speed * Time.deltaTime * -1,speed * Time.deltaTime * dir));
			if(transform.position.y + speed * Time.deltaTime *dir > upperBound || transform.position.y +speed * Time.deltaTime *dir < lowerBound){
				dir = dir*(-1);
			}

		} else {
			die ();
		}
	}
}


